swagger: "2.0"
info:
  title: Title
  description: Title
  version: 1.0.0
host: localhost:8080
schemes:
  - http

paths:
  /get:
    get:
      description: |
        型番と消費電力を返却
      responses:
        '200':
          description: |
            return to usage w
          schema:
            title: ArrayOfMachineinfo
            type: array
            properties:
              $ref: "#/definitions/MachineInfo"

definitions:
  MachineInfo:
    type: object
    properties:
      maker:
        type: string
      machine-number:
        type: string
      high-w:
        type: number
      low-w:
        type: number